apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      priorityClassName: high-elasticsearch-{{ .Values.namespace }}
      containers:
      - name: elasticsearch
        image: {{ .Values.image }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: cluster.name
          value: {{ .Values.clusterName }}
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.heapSize }} -Xmx{{ .Values.heapSize }} -Dlog4j2.disable.jmx=true"
        - name: xpack.security.enabled
          value: "{{ .Values.xpackSecurityEnabled }}"
        resources:
          limits:
            cpu: 1200m
            memory: 3000M
          requests:
            cpu: 1200m
            memory: 3000M
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-pdb
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      app: elasticsearch
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-elasticsearch-{{ .Values.namespace }}
value: 1000000
globalDefault: false
description: "This priority class is used for Elasticsearch pod."
---
apiVersion: v1
kind: Service
metadata:
  name: octane-es
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  selector:
    app: elasticsearch