apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      priorityClassName: high-elasticsearch-{{ .Release.Namespace }}
      containers:
      - name: elasticsearch
        image: {{ .Values.image }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: cluster.name
          value: {{ .Values.clusterName }}
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.heapSize }} -Xmx{{ .Values.heapSize }} -Dlog4j2.disable.jmx=true"
        resources:
          limits:
            cpu: 1200m
            memory: 3000M
          requests:
            cpu: 1200m
            memory: 3000M