apiVersion: v1
kind: Service
metadata:
  name: octane-es
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  selector:
    app: elasticsearch