apiVersion: v1
kind: Secret
metadata:
  name: '{{.Release.Name}}-octane-secrets'
  namespace: '{{.Release.Namespace}}'
type: Opaque
stringData:
  secret_env_file.properties: |
    SCHEMA_PASSWORD='{{.Values.db.schema.password}}'
    DB_ADMIN_USER='{{.Values.db.admin.user}}'
    DB_ADMIN_PASSWORD='{{.Values.db.admin.password}}'
    DB_LOGIN_USER='{{.Values.db.server.dbLoginUser}}'
    ELASTICSEARCH_USERNAME='{{.Values.elasticsearch.username}}'
    ELASTICSEARCH_PASSWORD='{{.Values.elasticsearch.password}}'
    INIT_STRING='{{.Values.initString}}'
    AUTH_TOKEN_ENCRYPTION_KEY='{{.Values.authTokenEncryptionKey}}'
    INTERNAL_CERTIFICATE='{{.Values.internalCertificate}}'