apiVersion: v1
kind: Service
metadata:
  name: octane-prod-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: octane
    hazelcast: {{ .Values.productionSlot }}
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/target-type: ip
    prometheus.io/port: "8443"
    prometheus.io/scrape: "true"
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: 8080
      name: http
{{- if contains "NodePort" .Values.service.type }}
  {{- if .Values.service.nodePort }}
      nodePort:  {{ .Values.service.nodePort }}
  {{- end }}
{{- end }}
    - port: 8443
      name: https
{{- if contains "NodePort" .Values.service.type }}
  {{- if .Values.service.httpsNodePort }}
      nodePort:  {{ .Values.service.httpsNodePort }}
  {{- end }}
{{- end }}
{{- if .Values.enableDebug }}
    - port: {{ .Values.debugPort }}
      name: debug
{{- end }}
  selector:
    app: octane
    slot: {{ .Values.productionSlot }}