kind: Service
apiVersion: v1
metadata:
  name: public-ingress-nginx
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.certificate}}
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: {{ .Values.cloudflareSg }}
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  loadBalancerSourceRanges:
  - 103.21.244.0/22
  ports:
  - name: https
    port: 443
    targetPort: 8443

