apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJteWR0YmxkMDA5Ny5ocGVzd2xhYi5uZXQ6ODA4MiI6IHsKCQkJImF1dGgiOiAiYm1kaFgyUmxkbTl3Y3pwdVoyRXVaR1YyTG05d2N5MDVOekk9IgoJCX0KCX0KfQ==

