apiVersion: v1
kind: PersistentVolume
metadata:
  name: octane-nfs-pv-{{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.global.storage }}
  accessModes:
    - ReadWriteMany
  claimRef:
    name: octane-claim
    namespace: {{ .Release.Namespace }}
  mountOptions:
    - hard
    - nfsvers=4.1
    - noresvport
  nfs:
   server: {{ .Values.nfs.server }}
   path: {{ .Values.nfs.path }}
