apiVersion: v1
kind: PersistentVolume
metadata:
  name: octane-nfs-pv-delete-{{ .Release.Namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: octane-claim-delete-dir
    namespace: {{ .Release.Namespace }}
  mountOptions:
    - hard
    - nfsvers=4.1
    - noresvport
  nfs:
   server: {{ .Values.nfs.server }}
   path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: octane-nfs-pv-delete-log-{{ .Release.Namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: octane-claim-delete-dir-log
    namespace: {{ .Release.Namespace }}
  mountOptions:
    - hard
    - nfsvers=4.1
    - noresvport
  nfs:
    server: {{ .Values.nfs.logServer }}
    path: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octane-claim-delete-dir
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octane-claim-delete-dir-log
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: delete-efs-dir
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: delete-efs-dir
      image: {{ .Values.image }}
      ports:
        - containerPort: 80
      command: ['sh', '-c']
      args:
        - mkdir -p /data/empty_dir;
          rsync -a --delete /data/empty_dir/ /data/{{- if .Values.octane.setEfsSubPath }}{{ .Release.Namespace }}/{{- end }}repo/;
          rsync -a --delete /data/empty_dir/ /data/logs/{{- if .Values.octane.setEfsSubPath }}{{ .Release.Namespace }}/{{- end }}logs/;
{{ if .Values.octane.deleteNamespaceDir }}
          rm -rf /data/{{- if .Values.octane.setEfsSubPath }}{{ .Release.Namespace }}/{{- end }};
          rm -rf /data/logs/{{- if .Values.octane.setEfsSubPath }}{{ .Release.Namespace }}/{{- end }};
{{- end }}
      volumeMounts:
      - mountPath: "/data"
        name: octane-nfs
      - mountPath: "/data/logs"
        name: octane-nfs-log
  volumes:
  - name: octane-nfs
    persistentVolumeClaim:
      claimName: octane-claim-delete-dir
  - name: octane-nfs-log
    persistentVolumeClaim:
      claimName: octane-claim-delete-dir-log
  restartPolicy: Never
